name: Build LaTeX resume

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Rename to resume.pdf
        run: mv main.pdf resume.pdf
      - name: Commit the latest resume
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add resume.pdf
          git commit -am "Update resume"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
