name: Build LaTeX resume

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Compress PDF
        uses: jy95/ghostscript-action@v1
        with:
          file: 'main.pdf'
          output: 'resume.pdf'
          arbitrary-parameters: '-dBATCH -dNOPAUSE -dSAFER -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -dDownsampleGrayImages=true -dDownsampleColorImages=true -dDownsampleMonoImages=true -dColorImageDownsampleType=/Bicubic -dColorImageResolution=200 -dGrayImageDownsampleType=/Bicubic -dGrayImageResolution=200 -dMonoImageDownsampleType=/Bicubic -dMonoImageResolution=200 -dEmbedAllFonts=true -dSubsetFonts=true'
      - name: Commit the latest resume
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add resume.pdf
          git commit -am "Update resume"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
